"""Markdown verdict reporter for ControlGate."""

from __future__ import annotations

from controlgate.models import Action, Verdict

_STATUS_EMOJI = {
    Action.BLOCK.value: "🚫",
    Action.WARN.value: "⚠️",
    Action.PASS.value: "✅",
}

_GATE_NAMES = {
    "secrets": "🔑 Secrets",
    "crypto": "🔒 Crypto",
    "iam": "🛡️ IAM",
    "sbom": "📦 Supply Chain",
    "iac": "🏗️ IaC",
    "input_validation": "✅ Input Validation",
    "audit": "📋 Audit",
    "change_control": "🔄 Change Control",
}


class MarkdownReporter:
    """Render a Verdict as human-readable Markdown."""

    def render(self, verdict: Verdict) -> str:
        """Render the verdict as a Markdown string.

        Suitable for PR comments, terminal output, or compliance reports.
        """
        emoji = _STATUS_EMOJI.get(verdict.verdict, "❓")
        lines = [
            f"# {emoji} ControlGate Verdict: **{verdict.verdict}**",
            "",
            f"> **Baseline**: {verdict.baseline_target} · **Scan**: {verdict.timestamp}",
            "",
            f"**Summary**: {verdict.summary}",
            "",
        ]

        # Gate summary table
        lines.append("## Gate Results")
        lines.append("")
        lines.append("| Gate | Status | Findings |")
        lines.append("|------|--------|----------|")
        for gate_id, gs in verdict.gate_summary.items():
            gate_label = _GATE_NAMES.get(gate_id, gate_id)
            status_emoji = _STATUS_EMOJI.get(gs.status, "❓")
            lines.append(f"| {gate_label} | {status_emoji} {gs.status} | {gs.findings} |")
        lines.append("")

        # Block / Warn findings detail
        block_findings = [f for f in verdict.findings if f.action == Action.BLOCK.value]
        warn_findings = [f for f in verdict.findings if f.action == Action.WARN.value]

        if block_findings:
            lines.append("## 🚫 Blocking Findings")
            lines.append("")
            for f in block_findings:
                lines.extend(self._render_finding(f))
            lines.append("")

        if warn_findings:
            lines.append("## ⚠️ Warnings")
            lines.append("")
            for f in warn_findings:
                lines.extend(self._render_finding(f))
            lines.append("")

        if not block_findings and not warn_findings:
            lines.append("## ✅ All clear — no security issues detected")
            lines.append("")

        lines.append("---")
        lines.append(
            "*Generated by [ControlGate](https://github.com/controlgate) · NIST SP 800-53 Rev. 5*"
        )

        return "\n".join(lines)

    def _render_finding(self, finding) -> list[str]:
        """Render a single finding as Markdown."""
        return [
            f"### `{finding.control_id}` — {finding.control_name}",
            "",
            f"- **Gate**: {_GATE_NAMES.get(finding.gate, finding.gate)}",
            f"- **Severity**: {finding.severity}"
            + (" (non-negotiable)" if finding.non_negotiable else ""),
            f"- **File**: `{finding.file}:{finding.line}`",
            f"- **Issue**: {finding.description}",
            f"- **Evidence**: `{finding.evidence}`",
            f"- **Remediation**: {finding.remediation}",
            "",
        ]

    def write(self, verdict: Verdict, output_path: str) -> None:
        """Write the verdict to a Markdown file."""
        from pathlib import Path

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(verdict), encoding="utf-8")
